### PR TITLE
Added top tracks information to display on the artists.html, as well …

### PR DESCRIPTION
**Pull request by JSirisavath**
Added top track information to display on the artists.html as well as grabbed a few more data from spotifyAPI for top tracks

### CODE REVIEW

**Comment by JSirisavath** [comment]
Part of issue ticket #10

**Comment by JSirisavath** [comment]
Hello all, this is still in progress, but here is implementation for the top tracks to HTML including a demo listen from few top tracks - All that is needed are the YT vids to display and some styling fixes

**Review by RichardJThies — CHANGES_REQUESTED** [review]
I changed into your branch, and ran it. Seems like things are working on the happy path. It definitely looks a lot better running than the old version on the visual side too. 

There does seem to be some odd things that need to be cleaned up though, like now there is a double “# safer - return None if no username” comment in app.py, so some slight clean up on the comments could be done. 

Also, the buttons are kind of blending into the background colors and are kind of hard to see at a glance. The submit, return to main page, and save buttons could all use a distinct style to make them easily visible on the web page.

**Review by cr7st74n — APPROVED** [review]

**Comment by cr7st74n** [comment]
Just fix any conflict that you could have with the main branch. Thank you

**Comment by JSirisavath** [comment]
@cr7st74n thank you!

**Comment by JSirisavath** [comment]
@RichardJThies, I made a lot of the styling on this recent commit and made sure your vids are in a relative spot on the artist.html page. I fixed BTN styling as well as most notably, changed the YouTube video fetch count to 20 instead of 5 on your file. 

@cr7st74n, Please review it too if you can, and if you want make any style changes.

**Review by RichardJThies — APPROVED** [review]
Hello @JSirisavath, I have looked over your changes to the visual presentation, and the buttons are definitely popping out better, which is good. I also noticed that you made some changes to the YT API. sending the width and height now seem a bit unnecessary it seems like. Changing up to 20 results is also fine.
I am also in the process of refactoring the API to shore up the module for exception handling and unit tests coming soon. So that will be an interesting merge conflict.

**Comment by JSirisavath** [comment]
@RichardJThies, yea when I tried the sizes to html page, it was very large and hard to  place inside sections. So I just used the custom sizes the was very identical to top tracks pictures  - And 20 so viewers have more videos to look at.  Thanks!

**Pull request merged**
