### PR TITLE
Added a .env example file to copy for other team members. Teamates ca…

### PR DESCRIPTION
**Pull request by JSirisavath**
Added a .env example file to copy for other team members. Teammates can add their api key inside their own copy of the .env file. Also, modified the Spotify API to source the .env file using decouple library as a reference

Issue ref #24

### CODE REVIEW

**Comment by JSirisavath** [comment]
Hi all, please review these changes and where we would use the .env file to source our API keys for our API key modules. I left detailed notes and instructions to set up  and be able to put your sensitive keys in a .env file for this project.

**Review by RichardJThies — COMMENTED** [review]
I do have a question concerning this .env concept @JSirisavath. 
Are these changes live/ or at least expected in the current main version? I was working on my own YT API brance, and your recent pull request branch using the old, environment variable based spotify API as far as I know. They both ran without issue. 
Will the current main version require the use of a .env file to run? I haven't configured my YT API use one yet.

**Comment by JSirisavath** [comment]
@RichardJThies, make a .env file (copy of the .env example file), put your own keys there (YOUR SPOTIFY AND YOUTUBE AND IF THERE IS, MUSICBRAINZ (create a variable for it) API KEYS) When you make it, follow the steps I posted on the file instructions on how to use them. If you need help, just move on to the other issues made on GitHub please. 

The .env is just a Q.O.L change for easier and secured way to use your api keys in your file long term and where as each team member is responsible for their own keys.

**Review by cr7st74n — APPROVED** [review]
Great idea to store our own keys in this env file

**Pull request merged**
