### PR TITLE
Its time to test some errors

### PR DESCRIPTION
**Pull request by dakota-bruffett**
Hey can someone look at the errorhandling code i put on for the project

### CODE REVIEW

**Comment by RichardJThies** [comment]
Hmm, I don't recall using cursors back during the week when we went over SQLite db, but everything looks ok. The program seems to run. What exactly were you testing for?

**Review by JSirisavath — CHANGES_REQUESTED** [review]
Request changes

**Review by JSirisavath — APPROVED** [review]
Good stuff - Will merge

**Comment by JSirisavath** [comment]
Continuous implementation on error handling to be added in the future. Will merge this one for now. Part of issue #28

**Pull request merged**
