### PR TITLE
App

### PR DESCRIPTION
**Pull request by dakota-bruffett**
Hey i ran into a pycharm issue had to rebuild the data base file

### CODE REVIEW

**Comment by cr7st74n** [comment]
No problem, thank you for the update!

**Comment by JSirisavath** [comment]
@dakota-bruffett Did you figure it out?

**Comment by dakota-bruffett** [comment]
i figured it out now im trying to get the flask and database to communicate

**Comment by JSirisavath** [comment]
A "Panic" thing was created. mentioned that the database files were lost in some time ago,  and needed to be "rebuilt".

**Pull request closed without merging**
