### PR TITLE
Merge (Database saving feature)

### PR DESCRIPTION
**Pull request by dakota-bruffett**
hey i think i figured it out can someone review it

### CODE REVIEW

**Review by JSirisavath — APPROVED** [review]
approved

**Comment by JSirisavath** [comment]
It seems like the db is saving username to session - @cr7st74n, can you also revew this since you two are working together

**Comment by JSirisavath** [comment]
Part of issue ref: #9

**Review by cr7st74n — APPROVED** [review]
Great guys, ready to save into db

**Pull request merged**
